/* Encrypted Client Hello (src/proto/tls/ech.c) on the real crypto library: ECHConfigList parsing,
 * HPKE against a known answer, and the shape of the outer Hello. Runs in `make crypto-test`.
 *
 * The known answer (enc, ct below) was produced by this code and then DECRYPTED by Go 1.27's
 * crypto/hpke, once, by hand (a 30-line program that reads the private key, enc, aad, ct and info
 * and prints the plaintext), for both AES-128-GCM and ChaCha20-Poly1305. Here it guards against an
 * accidental change of the key schedule; that a server accepts the whole payload is checked by
 * tests/ech.sh against Xray-core.
 *
 * The config lists are real: one generated by `xray tls ech` (nine cipher suites) and the one
 * Cloudflare publishes (the HTTPS record of cloudflare-ech.com). */
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "ech.h"
#include "reality.h"
#include "scrypto.h"

static int g_fail;
static void check(const char *what, int ok) {
    printf("%-78s %s\n", what, ok ? "ok" : "FAIL");
    if (!ok) g_fail++;
}

static int unhex(const char *h, uint8_t *out, size_t cap) {
    size_t n = strlen(h) / 2;
    if (n > cap) return -1;
    for (size_t i = 0; i < n; i++) {
        unsigned v;
        if (sscanf(h + 2 * i, "%2x", &v) != 1) return -1;
        out[i] = (uint8_t)v;
    }
    return (int)n;
}

/* Finds extension type t in a ClientHello body (without the message header); 1 if found. */
static int find_ext(const uint8_t *b, size_t bn, unsigned t, const uint8_t **d, size_t *dn) {
    size_t p = 34;
    if (bn < 36) return 0;
    p += 1 + b[p];
    p += 2 + ((size_t)b[p] << 8 | b[p + 1]);
    p += 1 + b[p];
    if (p + 2 > bn) return 0;
    size_t en = (size_t)b[p] << 8 | b[p + 1], q = p + 2;
    if (q + en != bn) return 0;
    while (q + 4 <= bn) {
        unsigned et = b[q] << 8 | b[q + 1];
        size_t el = (size_t)b[q + 2] << 8 | b[q + 3];
        if (et == t) { *d = b + q + 4; *dn = el; return 1; }
        q += 4 + el;
    }
    return 0;
}

static const char XRAY_LIST[] =
    "AGH+DQBdAAAgACBKucSK28OK1Tj2jNOOe7CewFXPruMgsl39t6zFkD2HegAkAAEAAQABAAIAAQADAAIAAQACAAIAAgADAAMAAQADAAIAAwADAA5wdWJsaWMuZXhhbXBsZQAA";
static const char CF_LIST[] =
    "AEX+DQBBNwAgACANG785NbYxf2vAoHiUugO7PDLchnWNz2f+95epg2DJewAEAAEAAQASY2xvdWRmbGFyZS1lY2guY29tAAA=";

int main(void) {
    uint8_t list[1100];
    struct ech_cfg c;
    int n;

    n = ech_b64_decode(XRAY_LIST, list, sizeof list);
    check("Xray: list decoded (99 bytes)", n == 99);
    check("Xray: a config picked", ech_pick(list, (size_t)n, &c) == 0);
    check("Xray: id 0, HKDF-SHA256 + AES-128-GCM (first suite), maximum_name_length 0",
          c.config_id == 0 && c.kdf_id == 1 && c.aead_id == 1 && c.max_name == 0);
    check("Xray: public_name public.example", !strcmp(c.public_name, "public.example"));

    n = ech_b64_decode(CF_LIST, list, sizeof list);
    check("Cloudflare: a config picked", ech_pick(list, (size_t)n, &c) == 0);
    check("Cloudflare: cloudflare-ech.com, maximum_name_length 0, id 0x37",
          !strcmp(c.public_name, "cloudflare-ech.com") && c.max_name == 0 && c.config_id == 0x37);

    n = ech_b64_decode(CF_LIST, list, sizeof list);
    list[1] ^= 1;
    check("list with a wrong length: parse error", ech_pick(list, (size_t)n, &c) == ECH_EPARSE);
    list[1] ^= 1;
    list[2] = 0xfe; list[3] = 0x0c;
    check("config of a foreign version skipped: no config left", ech_pick(list, (size_t)n, &c) == ECH_ENOCONFIG);
    list[3] = 0x0d;
    list[8] = 0x21;                                          /* kem_id 0x0021 (X448) */
    check("KEM other than X25519 skipped: no config left", ech_pick(list, (size_t)n, &c) == ECH_ENOCONFIG);
    check("garbage instead of base64 rejected", ech_b64_decode("!!!", list, sizeof list) < 0);

    /* HPKE known answer, with a config list built here around a known key. */
    uint8_t skR[32], pkR[32];
    for (int i = 0; i < 32; i++) skR[i] = (uint8_t)(i * 7 + 1);
    sc_x25519_base(pkR, skR);
    uint8_t cfg[200], lst[220];
    size_t k = 0;
    cfg[k++] = 0xfe; cfg[k++] = 0x0d;
    size_t lp = k; k += 2;
    cfg[k++] = 7; cfg[k++] = 0; cfg[k++] = 0x20; cfg[k++] = 0; cfg[k++] = 32; memcpy(cfg + k, pkR, 32); k += 32;
    cfg[k++] = 0; cfg[k++] = 8; cfg[k++] = 0; cfg[k++] = 1; cfg[k++] = 0; cfg[k++] = 1; cfg[k++] = 0; cfg[k++] = 1; cfg[k++] = 0; cfg[k++] = 3;
    cfg[k++] = 32; cfg[k++] = 14; memcpy(cfg + k, "public.example", 14); k += 14; cfg[k++] = 0; cfg[k++] = 0;
    cfg[lp] = (uint8_t)((k - lp - 2) >> 8); cfg[lp + 1] = (uint8_t)(k - lp - 2);
    lst[0] = (uint8_t)(k >> 8); lst[1] = (uint8_t)k; memcpy(lst + 2, cfg, k);
    check("hand-built list: config picked, maximum_name_length 32", ech_pick(lst, k + 2, &c) == 0 && c.max_name == 32);

    static const struct { int aead; const char *enc, *ct; } KAT[] = {
        { 1, "79a631eede1bf9c98f12032cdeadd0e7a079398fc786b88cc846ec89af85a51a",
             "af87037334647bec97c95ffb3bbbdf6f52f968e7c1f7a3dd1b16cec061dda9111fd4fdc27275b3dc2f24bd753e" },
        { 3, "79a631eede1bf9c98f12032cdeadd0e7a079398fc786b88cc846ec89af85a51a",
             "12ded18e962790ed0538a212973bf9b55c7944f851db8c4e052a1c54dfc1b1f06783125f0bb6d8e7e570a9beb8" },
    };
    for (int i = 0; i < 2; i++) {
        c.aead_id = (uint16_t)KAT[i].aead;
        uint8_t eph[32], enc[32], ct[64], want_enc[32], want_ct[64];
        for (int j = 0; j < 32; j++) eph[j] = (uint8_t)(0x40 + j);
        const char *pt = "Beauty is truth, truth beauty", *aad = "aad-bytes-0123";
        int rc = ech_hpke_seal(&c, eph, (const uint8_t *)aad, strlen(aad), (const uint8_t *)pt, strlen(pt), enc, ct);
        int wn = unhex(KAT[i].ct, want_ct, sizeof want_ct);
        unhex(KAT[i].enc, want_enc, sizeof want_enc);
        char what[160];
        snprintf(what, sizeof what, "HPKE %s: enc and ciphertext match the values Go decrypted",
                 KAT[i].aead == 1 ? "AES-128-GCM" : "ChaCha20-Poly1305");
        check(what, rc == 0 && wn == (int)strlen(pt) + 16 && !memcmp(enc, want_enc, 32) && !memcmp(ct, want_ct, (size_t)wn));
    }

    /* The outer Hello around a Hello from the real builder (Chrome shape, GREASE ECH, TLS 1.2 in
     * supported_versions). */
    c.aead_id = 1;
    struct reality_cfg rcfg = { .sni = "secret.example", .plain = 1, .pq = 1, .fp = "chrome" };
    struct reality_state rst;
    static unsigned char hello[2560], outer[6144];
    size_t hn = 0, on = 0;
    static struct ech_state es;
    check("Hello built by reality_build_hello", reality_build_hello(&rcfg, &rst, hello, sizeof hello, &hn) == 0);
    check("ech_wrap: outer Hello built", ech_wrap(&c, hello, hn, outer, sizeof outer, &on, &es) == 0);
    check("  TLS record: header length matches", on > 5 && (size_t)(outer[3] << 8 | outer[4]) + 5 == on);
    check("  real name absent from the outer Hello", memmem(outer, on, "secret.example", 14) == NULL);
    check("  public_name present in the outer Hello", memmem(outer, on, "public.example", 14) != NULL);
    check("  inner Hello carries the real name", memmem(es.inner, es.inner_n, "secret.example", 14) != NULL);
    check("  inner random is the built Hello's, outer random differs",
          !memcmp(es.random, hello + 11, 32) && memcmp(outer + 11, hello + 11, 32) != 0);
    check("  both carry the same session_id", outer[43] == hello[43] && !memcmp(outer + 44, hello + 44, hello[43]));
    check("  inner: a ClientHello message, length matches",
          es.inner[0] == 1 && ((size_t)es.inner[1] << 16 | (size_t)es.inner[2] << 8 | es.inner[3]) + 4 == es.inner_n);
    const uint8_t *vi, *vo;
    size_t vin, von;
    int fi = find_ext(es.inner + 4, es.inner_n - 4, 0x002b, &vi, &vin);
    int fo = find_ext(outer + 9, on - 9, 0x002b, &vo, &von);
    int has12_in = 0, has12_out = 0, has13_in = 0;
    for (size_t q = 1; fi && q + 1 < vin; q += 2) { unsigned v = vi[q] << 8 | vi[q + 1]; has12_in |= v == 0x0303; has13_in |= v == 0x0304; }
    for (size_t q = 1; fo && q + 1 < von; q += 2) has12_out |= (vo[q] << 8 | vo[q + 1]) == 0x0303;
    check("  inner supported_versions: TLS 1.3 present, TLS 1.2 absent", fi && has13_in && !has12_in);
    check("  outer supported_versions keeps TLS 1.2 (Chrome shape)", fo && has12_out);
    const uint8_t *ei;
    size_t ein;
    check("  ECH ext: inner (type 1) in the inner Hello, outer (type 0) in the outer",
          find_ext(es.inner + 4, es.inner_n - 4, 0xfe0d, &ei, &ein) && ein == 1 && ei[0] == 1 &&
          find_ext(outer + 9, on - 9, 0xfe0d, &ei, &ein) && ein > 100 && ei[0] == 0);

    printf(g_fail ? "echmatch: %d FAILED\n" : "echmatch: all checks passed\n", g_fail);
    return g_fail ? 1 : 0;
}
