/* Encrypted Client Hello (src/proto/tls/ech.c) on the real crypto library: ECHConfigList parsing,
 * HPKE against a known answer, and the shape of the outer Hello. Runs in `make crypto-test`.
 *
 * The known answer (enc, ct below) was produced by this code and then DECRYPTED by Go 1.27's
 * crypto/hpke, once, by hand (a 30-line program that reads the private key, enc, aad, ct and info
 * and prints the plaintext), for both AES-128-GCM and ChaCha20-Poly1305; circl's hpke (v1.6.5)
 * decrypts it too. Here it guards against an accidental change of the key schedule. It also
 * vouches for the test's own HPKE open (hpke_open below, written from RFC 9180), which then opens
 * the payload of the outer Hello: Inner, padded, sealed against the outer Hello as AAD. That a
 * real server accepts it all is checked by tests/ech.sh against Xray-core.
 *
 * The config lists are real: one generated by `xray tls ech` (nine cipher suites) and the one
 * Cloudflare publishes (the HTTPS record of cloudflare-ech.com). */
#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "ech.h"
#include "reality.h"
#include "scrypto.h"

static int g_fail;
static void check(const char *what, int ok) {
    printf("%-78s %s\n", what, ok ? "ok" : "FAIL");
    if (!ok) g_fail++;
}

static int unhex(const char *h, uint8_t *out, size_t cap) {
    size_t n = strlen(h) / 2;
    if (n > cap) return -1;
    for (size_t i = 0; i < n; i++) {
        unsigned v;
        if (sscanf(h + 2 * i, "%2x", &v) != 1) return -1;
        out[i] = (uint8_t)v;
    }
    return (int)n;
}

/* Finds extension type t in a ClientHello body (without the message header); 1 if found. */
static int find_ext(const uint8_t *b, size_t bn, unsigned t, const uint8_t **d, size_t *dn) {
    size_t p = 34;
    if (bn < 36) return 0;
    p += 1 + b[p];
    p += 2 + ((size_t)b[p] << 8 | b[p + 1]);
    p += 1 + b[p];
    if (p + 2 > bn) return 0;
    size_t en = (size_t)b[p] << 8 | b[p + 1], q = p + 2;
    if (q + en != bn) return 0;
    while (q + 4 <= bn) {
        unsigned et = b[q] << 8 | b[q + 1];
        size_t el = (size_t)b[q + 2] << 8 | b[q + 3];
        if (et == t) { *d = b + q + 4; *dn = el; return 1; }
        q += 4 + el;
    }
    return 0;
}

/* An ECHConfigList of one config (version 0xfe0d, id 7, KEM X25519, maximum_name_length 32)
 * around pk, with the given (kdf, aead) pairs, public_name and extensions; returns its length.
 * The ECHConfig itself starts at lst + 2. */
static size_t make_list(uint8_t *lst, const uint8_t pk[32], const uint16_t *suites, size_t ns,
                        const char *name, const uint8_t *ext, size_t ext_n) {
    uint8_t *cfg = lst + 2;
    size_t k = 0, nn = strlen(name);
    cfg[k++] = 0xfe; cfg[k++] = 0x0d;
    size_t lp = k;
    k += 2;
    cfg[k++] = 7; cfg[k++] = 0; cfg[k++] = 0x20; cfg[k++] = 0; cfg[k++] = 32;
    memcpy(cfg + k, pk, 32); k += 32;
    cfg[k++] = 0; cfg[k++] = (uint8_t)(ns * 4);
    for (size_t i = 0; i < 2 * ns; i++) {
        cfg[k++] = (uint8_t)(suites[i] >> 8);
        cfg[k++] = (uint8_t)suites[i];
    }
    cfg[k++] = 32;
    cfg[k++] = (uint8_t)nn; memcpy(cfg + k, name, nn); k += nn;
    cfg[k++] = (uint8_t)(ext_n >> 8); cfg[k++] = (uint8_t)ext_n;
    if (ext_n) memcpy(cfg + k, ext, ext_n);
    k += ext_n;
    cfg[lp] = (uint8_t)((k - lp - 2) >> 8); cfg[lp + 1] = (uint8_t)(k - lp - 2);
    lst[0] = (uint8_t)(k >> 8); lst[1] = (uint8_t)k;
    return k + 2;
}

/* LabeledExtract (expand 0) and LabeledExpand (expand 1) of RFC 9180, 4, with HKDF-SHA256. */
static int labeled(int expand, const uint8_t *suite, size_t sn, const uint8_t *key, size_t key_n,
                   const char *label, const uint8_t *in, size_t in_n, size_t L, uint8_t *out) {
    uint8_t b[1300];
    size_t i = 0;
    if (expand) { b[i++] = (uint8_t)(L >> 8); b[i++] = (uint8_t)L; }
    memcpy(b + i, "HPKE-v1", 7); i += 7;
    memcpy(b + i, suite, sn); i += sn;
    memcpy(b + i, label, strlen(label)); i += strlen(label);
    if (in_n) memcpy(b + i, in, in_n);
    i += in_n;
    return expand ? sc_hkdf_expand(SC_SHA256, key, key_n, b, i, out, L)
                  : sc_hkdf_extract(SC_SHA256, key, key_n, b, i, out);
}

/* HPKE base mode, the receiver's side (RFC 9180, 4.1 and 5.1), DHKEM(X25519, HKDF-SHA256) and
 * HKDF-SHA256; info = "tls ech\0" || ECHConfig. Opens ct (ct_n bytes with the tag) in place. */
static int hpke_open(const uint8_t skR[32], unsigned aead, const uint8_t *config, size_t config_n,
                     const uint8_t enc[32], const uint8_t *aad, size_t aad_n,
                     uint8_t *ct, size_t ct_n) {
    static const uint8_t KEM[5] = { 'K', 'E', 'M', 0x00, 0x20 };
    const uint8_t suite[10] = { 'H', 'P', 'K', 'E', 0x00, 0x20, 0x00, 0x01, 0x00, (uint8_t)aead };
    uint8_t dh[32], kctx[64], prk[32], shared[32], ksc[65], secret[32], key[32], nonce[12];
    uint8_t info[1100];
    enum sc_aead_alg alg = aead == 3 ? SC_CHACHA20_POLY1305 : SC_AES128_GCM;
    if (ct_n < 16 || config_n > sizeof info - 8) return -1;
    memcpy(info, "tls ech", 8);
    memcpy(info + 8, config, config_n);
    memcpy(kctx, enc, 32);
    ksc[0] = 0;
    if (sc_x25519(dh, skR, enc) || sc_x25519_base(kctx + 32, skR) ||
        labeled(0, KEM, 5, NULL, 0, "eae_prk", dh, 32, 0, prk) ||
        labeled(1, KEM, 5, prk, 32, "shared_secret", kctx, 64, 32, shared) ||
        labeled(0, suite, 10, NULL, 0, "psk_id_hash", NULL, 0, 0, ksc + 1) ||
        labeled(0, suite, 10, NULL, 0, "info_hash", info, 8 + config_n, 0, ksc + 33) ||
        labeled(0, suite, 10, shared, 32, "secret", NULL, 0, 0, secret) ||
        labeled(1, suite, 10, secret, 32, "key", ksc, 65, sc_aead_key_len(alg), key) ||
        labeled(1, suite, 10, secret, 32, "base_nonce", ksc, 65, 12, nonce))
        return -1;
    struct sc_aead k;
    if (sc_aead_setkey(&k, alg, key)) return -1;
    int rc = sc_aead_open(&k, nonce, aad, aad_n, ct, ct_n - 16, ct + ct_n - 16);
    sc_aead_free(&k);
    return rc;
}

static const char XRAY_LIST[] =
    "AGH+DQBdAAAgACBKucSK28OK1Tj2jNOOe7CewFXPruMgsl39t6zFkD2HegAkAAEAAQABAAIAAQADAAIAAQACAAIAAgADAAMAAQADAAIAAwADAA5wdWJsaWMuZXhhbXBsZQAA";
static const char CF_LIST[] =
    "AEX+DQBBNwAgACANG785NbYxf2vAoHiUugO7PDLchnWNz2f+95epg2DJewAEAAEAAQASY2xvdWRmbGFyZS1lY2guY29tAAA=";

int main(void) {
    uint8_t list[1100];
    struct ech_cfg c;
    int n;

    n = ech_b64_decode(XRAY_LIST, list, sizeof list);
    check("Xray: list decoded (99 bytes)", n == 99);
    check("Xray: a config picked", ech_pick(list, (size_t)n, &c) == 0);
    check("Xray: id 0, HKDF-SHA256 + AES-128-GCM (first suite), maximum_name_length 0",
          c.config_id == 0 && c.kdf_id == 1 && c.aead_id == 1 && c.max_name == 0);
    check("Xray: public_name public.example", !strcmp(c.public_name, "public.example"));

    n = ech_b64_decode(CF_LIST, list, sizeof list);
    check("Cloudflare: a config picked", ech_pick(list, (size_t)n, &c) == 0);
    check("Cloudflare: cloudflare-ech.com, maximum_name_length 0, id 0x37",
          !strcmp(c.public_name, "cloudflare-ech.com") && c.max_name == 0 && c.config_id == 0x37);

    n = ech_b64_decode(CF_LIST, list, sizeof list);
    list[1] ^= 1;
    check("list with a wrong length: parse error", ech_pick(list, (size_t)n, &c) == ECH_EPARSE);
    list[1] ^= 1;
    list[2] = 0xfe; list[3] = 0x0c;
    check("config of a foreign version skipped: no config left", ech_pick(list, (size_t)n, &c) == ECH_ENOCONFIG);
    list[3] = 0x0d;
    list[8] = 0x21;                                          /* kem_id 0x0021 (X448) */
    check("KEM other than X25519 skipped: no config left", ech_pick(list, (size_t)n, &c) == ECH_ENOCONFIG);
    check("garbage instead of base64 rejected", ech_b64_decode("!!!", list, sizeof list) < 0);
    check("base64 longer than the buffer rejected", ech_b64_decode(XRAY_LIST, list, 98) < 0);

    /* HPKE known answer, with a config list built here around a known key. */
    uint8_t skR[32], pkR[32];
    for (int i = 0; i < 32; i++) skR[i] = (uint8_t)(i * 7 + 1);
    sc_x25519_base(pkR, skR);
    uint8_t lst[220];
    static const uint16_t SUITES[] = { 1, 1, 1, 3 };
    size_t ln = make_list(lst, pkR, SUITES, 2, "public.example", NULL, 0), cfg_n = ln - 2;
    check("hand-built list: config picked, maximum_name_length 32",
          ech_pick(lst, ln, &c) == 0 && c.max_name == 32);

    static const struct { int aead; const char *enc, *ct; } KAT[] = {
        { 1, "79a631eede1bf9c98f12032cdeadd0e7a079398fc786b88cc846ec89af85a51a",
             "af87037334647bec97c95ffb3bbbdf6f52f968e7c1f7a3dd1b16cec061dda9111fd4fdc27275b3dc2f24bd753e" },
        { 3, "79a631eede1bf9c98f12032cdeadd0e7a079398fc786b88cc846ec89af85a51a",
             "12ded18e962790ed0538a212973bf9b55c7944f851db8c4e052a1c54dfc1b1f06783125f0bb6d8e7e570a9beb8" },
    };
    for (int i = 0; i < 2; i++) {
        c.aead_id = (uint16_t)KAT[i].aead;
        uint8_t eph[32], enc[32], ct[64], want_enc[32], want_ct[64];
        for (int j = 0; j < 32; j++) eph[j] = (uint8_t)(0x40 + j);
        const char *pt = "Beauty is truth, truth beauty", *aad = "aad-bytes-0123";
        int rc = ech_hpke_seal(&c, eph, (const uint8_t *)aad, strlen(aad), (const uint8_t *)pt, strlen(pt), enc, ct);
        int wn = unhex(KAT[i].ct, want_ct, sizeof want_ct);
        unhex(KAT[i].enc, want_enc, sizeof want_enc);
        char what[160];
        snprintf(what, sizeof what, "HPKE %s: enc and ciphertext match the values Go decrypted",
                 KAT[i].aead == 1 ? "AES-128-GCM" : "ChaCha20-Poly1305");
        check(what, rc == 0 && wn == (int)strlen(pt) + 16 && !memcmp(enc, want_enc, 32) && !memcmp(ct, want_ct, (size_t)wn));
        snprintf(what, sizeof what, "HPKE %s: the test's own open recovers the plaintext",
                 KAT[i].aead == 1 ? "AES-128-GCM" : "ChaCha20-Poly1305");
        check(what, wn > 16 && !hpke_open(skR, (unsigned)KAT[i].aead, lst + 2, cfg_n, want_enc,
                                          (const uint8_t *)aad, strlen(aad), want_ct, (size_t)wn) &&
                    !memcmp(want_ct, pt, strlen(pt)));
    }

    /* Configs ech_pick passes over, each in a list of its own around the same key. */
    struct ech_cfg o;
    static const uint16_t SKIP[] = { 2, 1, 1, 2, 1, 3 };
    ln = make_list(list, pkR, SKIP, 3, "public.example", NULL, 0);
    check("suites with HKDF-SHA384 or AES-256-GCM passed over for ChaCha20",
          ech_pick(list, ln, &o) == 0 && o.kdf_id == 1 && o.aead_id == 3);
    ln = make_list(list, pkR, SUITES, 2, "public.example", (const uint8_t *)"\xfa\xce\x00\x00", 4);
    check("config with a mandatory extension skipped", ech_pick(list, ln, &o) == ECH_ENOCONFIG);
    ln = make_list(list, pkR, SUITES, 2, "public.example", (const uint8_t *)"\x0a\xce\x00\x00", 4);
    check("config with an optional extension picked", ech_pick(list, ln, &o) == 0);
    ln = make_list(list, pkR, SUITES, 2, "public_example", NULL, 0);
    check("config with a public_name that is no host name skipped",
          ech_pick(list, ln, &o) == ECH_ENOCONFIG);

    /* The outer Hello around a Hello from the real builder (Chrome shape, GREASE ECH, TLS 1.2 in
     * supported_versions). With ChaCha20-Poly1305, the config's second suite: its aead_id (3)
     * differs from kdf_id (1), so the two fields cannot pass for each other. */
    c.aead_id = 3;
    struct reality_cfg rcfg = { .sni = "secret.example", .plain = 1, .pq = 1, .fp = "chrome" };
    struct reality_state rst;
    static unsigned char hello[2560], outer[6144];
    size_t hn = 0, on = 0;
    static struct ech_state es;
    check("Hello built by reality_build_hello", reality_build_hello(&rcfg, &rst, hello, sizeof hello, &hn) == 0);
    check("ech_wrap: outer Hello built", ech_wrap(&c, hello, hn, outer, sizeof outer, &on, &es) == 0);
    check("  TLS record: handshake, version 0x0301, header length matches",
          on > 5 && outer[0] == 0x16 && outer[1] == 3 && outer[2] == 1 &&
          (size_t)(outer[3] << 8 | outer[4]) + 5 == on);
    check("  real name absent from the outer Hello", memmem(outer, on, "secret.example", 14) == NULL);
    check("  public_name present in the outer Hello", memmem(outer, on, "public.example", 14) != NULL);
    check("  inner Hello carries the real name", memmem(es.inner, es.inner_n, "secret.example", 14) != NULL);
    check("  inner random is the built Hello's, outer random differs",
          !memcmp(es.random, hello + 11, 32) && memcmp(outer + 11, hello + 11, 32) != 0);
    check("  both carry the same session_id", outer[43] == hello[43] && !memcmp(outer + 44, hello + 44, hello[43]));
    check("  inner: a ClientHello message, length matches",
          es.inner[0] == 1 && ((size_t)es.inner[1] << 16 | (size_t)es.inner[2] << 8 | es.inner[3]) + 4 == es.inner_n);
    const uint8_t *vi, *vo;
    size_t vin, von;
    int fi = find_ext(es.inner + 4, es.inner_n - 4, 0x002b, &vi, &vin);
    int fo = find_ext(outer + 9, on - 9, 0x002b, &vo, &von);
    int has12_in = 0, has12_out = 0, has13_in = 0, grease_in = 0, grease_out = 0;
    for (size_t q = 1; fi && q + 1 < vin; q += 2) {
        unsigned v = vi[q] << 8 | vi[q + 1];
        has12_in |= v == 0x0303;
        has13_in |= v == 0x0304;
        grease_in += (v & 0x0F0F) == 0x0A0A && (v >> 8) == (v & 0xFF);
    }
    for (size_t q = 1; fo && q + 1 < von; q += 2) {
        unsigned v = vo[q] << 8 | vo[q + 1];
        has12_out |= v == 0x0303;
        grease_out += (v & 0x0F0F) == 0x0A0A && (v >> 8) == (v & 0xFF);
    }
    check("  inner supported_versions: GREASE and TLS 1.3 kept, TLS 1.2 dropped",
          fi && has13_in && !has12_in && grease_in == 1 && grease_out == 1);
    check("  outer supported_versions keeps TLS 1.2 (Chrome shape)", fo && has12_out);
    const uint8_t *ei;
    size_t ein;
    check("  ECH ext: inner (type 1) in the inner Hello, outer (type 0) in the outer",
          find_ext(es.inner + 4, es.inner_n - 4, 0xfe0d, &ei, &ein) && ein == 1 && ei[0] == 1 &&
          find_ext(outer + 9, on - 9, 0xfe0d, &ei, &ein) && ein > 100 && ei[0] == 0);

    /* The outer ECH extension: type(1) kdf(2) aead(2) config_id(1), enc with a 2-byte length,
     * payload with a 2-byte length. */
    const uint8_t *eo = NULL;
    size_t eon = 0, pay_n = 0;
    int fe = find_ext(outer + 9, on - 9, 0xfe0d, &eo, &eon) && eon > 42;
    if (fe) pay_n = (size_t)eo[40] << 8 | eo[41];
    check("  ECH ext: the config's suite and id, 32-byte enc, payload to the end",
          fe && (eo[1] << 8 | eo[2]) == c.kdf_id && (eo[3] << 8 | eo[4]) == c.aead_id &&
          eo[5] == c.config_id && c.config_id == 7 && (eo[6] << 8 | eo[7]) == 32 &&
          eon == 42 + pay_n);
    /* The payload opens with the server's key; the AAD is the outer ClientHello (no handshake
     * header) with the payload zeroed. Inside: EncodedClientHelloInner, which is Inner without its
     * legacy_session_id, then zeros: the name up to maximum_name_length, the whole up to a
     * multiple of 32 (RFC 9849, 5.1 and 6.1.3). */
    static uint8_t aad2[6144], pt2[6144];
    int op = -1;
    if (fe && pay_n > 16) {
        memcpy(aad2, outer + 9, on - 9);
        memset(aad2 + (eo + 42 - outer - 9), 0, pay_n);
        memcpy(pt2, eo + 42, pay_n);
        op = hpke_open(skR, c.aead_id, lst + 2, cfg_n, eo + 8, aad2, on - 9, pt2, pay_n);
    }
    check("  payload opens with the server's key, the outer Hello as AAD", op == 0);
    size_t sidn = es.inner[4 + 34], encn = es.inner_n - 4 - sidn, ptn = op == 0 ? pay_n - 16 : 0;
    int inner_ok = ptn >= encn && !memcmp(pt2, es.inner + 4, 34) && pt2[34] == 0 &&
                   !memcmp(pt2 + 35, es.inner + 4 + 35 + sidn, encn - 35);
    for (size_t i = encn; inner_ok && i < ptn; i++) inner_ok = pt2[i] == 0;
    check("  plaintext: Inner without session_id, then zeros", inner_ok);
    /* The padding for maximum_name_length 0..63, so that the sum meets every remainder mod 32:
     * at one value the rounding up hides an off-by-one in the name's part. */
    int pad_ok = 1;
    for (unsigned m = 0; m < 64 && pad_ok; m++) {
        static unsigned char o2[6144];
        static struct ech_state es2;
        struct ech_cfg c2 = c;
        size_t o2n = 0, want = encn + (m > 14 ? m - 14 : 0);  /* the name is 14 bytes */
        want += 31 - (want - 1) % 32;
        c2.max_name = (uint8_t)m;
        pad_ok = ech_wrap(&c2, hello, hn, o2, sizeof o2, &o2n, &es2) == 0 &&
                 find_ext(o2 + 9, o2n - 9, 0xfe0d, &eo, &eon) && eon > 42 &&
                 ((size_t)eo[40] << 8 | eo[41]) == want + 16;
    }
    check("  padding: the name to maximum_name_length (0..63), the whole to 32", pad_ok);

    printf(g_fail ? "echmatch: %d FAILED\n" : "echmatch: all checks passed\n", g_fail);
    return g_fail ? 1 : 0;
}
